{"uuid": "279b0012-9fe0-492f-9289-345abb738118", "children": ["d7c230af-f6fe-4ec7-a035-365dcf11e892", "2c63279d-1f96-459b-bffd-0e5460285a4a", "9b7f6d5b-b69a-48f3-864d-7f5cc51f3856"], "befores": [{"name": "xunit_setup_class_fixture_Testtest", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: missing 'name'\n  (Session info: chrome=94.0.4606.61)\n\n", "trace": "  File \"d:\\python37\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"d:\\python37\\lib\\site-packages\\_pytest\\python.py\", line 811, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"d:\\python37\\lib\\site-packages\\_pytest\\python.py\", line 739, in _call_with_optional_argument\n    func(arg)\n  File \"E:\\Test_case\\Python\\Demo_test\\case\\test_repeat.py\", line 19, in setup_class\n    self.driver.add_cookie({'COOKIE_SESSION': '55009_3_9_8_55_16_1_1_7_9_187_2_96_1512_0_0_1632665549_1632660983_1632720496%7C9%231495_324_1632660965%7C9'})\n  File \"d:\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 894, in add_cookie\n    self.execute(Command.ADD_COOKIE, {'cookie': cookie_dict})\n  File \"d:\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\python37\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1632800390407, "stop": 1632800392112}], "start": 1632800390407, "stop": 1632800392229}